# Inspections
inspection.missingExpectPlatform = Method ''{0}'' has no implementation for {1}
inspection.implementExpectPlatform = Create implementations
inspection.implementExpectPlatform.single = Implement for {0}
inspection.unsafePlatformOnlyCall = Unsafe call to platform-only method ''{0}''

inspection.expectPlatform.invalidBody=@PlatformImpl method body should only throw new AssertionError()
inspection.expectPlatform.missingBody=@PlatformImpl method is missing a body (should throw new AssertionError())
inspection.expectPlatform.replaceWithAssertion=Replace body with 'throw new AssertionError();'
inspection.expectPlatform.addBody=Add 'throw new AssertionError();' body

# Gutter
architectury.gutter.chooseCommon = Choose Common Declaration of {0} ({1} methods found)
architectury.gutter.chooseImpl = Choose Implementation of {0} ({1} methods found)
architectury.gutter.goToCommon = Go to common declaration
architectury.gutter.goToPlatform = Go to platform implementation



# Platforms
platform.fabric = Fabric
platform.forge = Forge
platform.neoforge = Neoforge
