# Inspections
inspection.missingExpectPlatform = Method ''{0}'' has no implementation for {1}
inspection.implementExpectPlatform = Create implementations
inspection.implementExpectPlatform.single = Implement for {0}
inspection.unsafePlatformOnlyCall = Unsafe call to platform-only method ''{0}''

inspection.expectPlatform.invalidBody=@PlatformImpl method body should only throw new AssertionError()
inspection.expectPlatform.missingBody=@PlatformImpl method is missing a body (should throw new AssertionError())
inspection.expectPlatform.replaceWithAssertion=Replace body with 'throw new AssertionError();'
inspection.expectPlatform.addBody=Add 'throw new AssertionError();' body

# Gutter
gutter.chooseCommon = Choose Common Declaration of {0} ({1} methods found)
gutter.chooseImpl = Choose Implementation of {0} ({1} methods found)
gutter.goToCommon = Go to common declaration
gutter.goToPlatform = Go to platform implementation
gutter.virtualOverride.tooltip=Virtual override in platform module(s)
gutter.virtualOverride.popup=<html>Choose platform override for <b>{0}</b> ({1} found)</html>


# Platforms
platform.fabric = Fabric
platform.forge = Forge
platform.neoforge = Neoforge
